name: turing_hunt_app
description: "Test app for Turing Treasure Hunt 2024."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  geolocator: ^10.1.0
  fluttertoast: ^8.2.5
  clipboard: ^0.1.3
  share: ^2.0.4
  location_picker_flutter_map: ^3.0.1
  latlong2: ^0.9.1

flutter:
  uses-material-design: true
